# Copyright 2021 Kidus Tiliksew

# This file is part of Tensor EMR.

# Tensor EMR is free software: you can redistribute it and/or modify
# it under the terms of the version 2 of GNU General Public License as published by
# the Free Software Foundation.

# Tensor EMR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


version: "3.2"

services:
  postgres:
    image: debezium/postgres:14
    container_name: postgres
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=emr
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    #  - ./postgres.conf:/etc/postgresql/postgresql.conf
    #  - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4:6.5
    container_name: pgadmin
    restart: "always"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  server:
    image: ghcr.io/tensor-systems/tensoremr-server:main
    ports:
      - "8080:8080"
    volumes:
      - serverfiles:/files
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=emr
      - DB_HOST=postgres
      #      DB_REPLICATION_HOST: "192.168.1.101"
      - DB_DRIVER=postgres
      - DB_PORT=5432
      - RXNORM_ADDRESS=https://rxnav.nlm.nih.gov
    depends_on:
      - postgres 

  webclient:
    image: ghcr.io/tensor-systems/tensoremr-web-client:main
    ports:
      - "4000:80"
    environment:
      NODE_ENV: "production"
      REACT_APP_SERVER_URL: http://localhost:8080
      REACT_APP_ELASTICSEARCH_URL: http://localhost:9200
    depends_on:
      - server

volumes:
  postgres:
  serverfiles:
